#!/bin/bash -l
#SBATCH -N 1
#SBATCH -n 1
#SBATCH -t 6:0:0
#SBATCH --mem 32G 
#SBATCH --ntasks-per-node 8
#SBATCH --gres=gpu:1

module load cudatoolkit/9.1
module load cudnn/cuda-9.1/7.1.2

source /home/dongdong/software/GMX20192plumed/bin/GMXRC.bash
source /home/linfengz/SCR/softwares/tf_venv_r1.8/bin/activate

gmx mdrun -deffnm md -nt 8  -plumed plumed.bf.dat 1> gmx_mdrun.log 2> gmx_mdrun.log
if test $? -eq 0; then
    touch tag_finished
fi
sleep 1
