#!/bin/bash -l
#SBATCH -N 1
#SBATCH -n 1
#SBATCH -t 22:0:0
#SBATCH --mem 32G 
#SBATCH --ntasks-per-node 2
#SBATCH --gres=gpu:1

module load cudatoolkit/9.1
module load cudnn/cuda-9.1/7.1.2

source /home/linfengz/SCR/softwares/tf_venv_r1.8/bin/activate

python compute_string.py

if test $? -eq 0; then
    touch tag_finished
fi
sleep 1
